### ISSUE TITLE
Question:  Why both flask and django

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/WOFpy#57] opened 2016-06-01 19:42 UTC
Why are both required/installed with the conda recipe?

**Comment by valentinedwv** [comment] 2016-06-01 20:47
Django needed for the ODM Web services, and not WofPy.

**Comment by emiliom** [comment] 2016-06-02 04:03
Which conda recipe are you referring to? [This one?](https://github.com/ODM2/conda-recipes-ODM2/blob/master/environment.yml) That recipe installs "everything", all ODM2 packages that have been packaged in the ODM2 channel so far. FYI, at this time that's mainly `odm2api`, `wofpy`, and dependencies.

I don't see any Django in the [conda recipe used to build the WOFpy conda package.](https://github.com/ODM2/conda-recipes-ODM2/blob/master/recipes/wofpy/meta.yaml) Though I'm not aware of other django dependencies loaded by the ODM2 generic conda environment, if it got installed it's almost certainly b/c it was needed by something -- just not WOFpy directly.

Pinging @ocefpaf, in case he has some additional insight/wisdom. Though like I said, I don't see a problem per se.

BTW, questions that are specific to conda packaging are probably better addressed as issues on the [conda-recipes-ODM2 repo](https://github.com/ODM2/conda-recipes-ODM2).

**Comment by emiliom** [comment] 2016-08-13 18:30
Following up on this .... I've confirmed that installing just wofpy from the odm2 channel does install django as a dependency. @valentinedwv's response, "Django needed for the ODM Web services, and not WofPy", suggests that django shouldn't be there.

@valentinedwv and @ocefpaf, can you track how it got to be a dependency on the conda package, and remove it if it truly isn't needed? Maybe it's a dependency on a dependency? I don't see it on the wofpy [setup.py](https://github.com/ODM2/WOFpy/blob/master/setup.py) or the conda recipe [meta.yaml](https://github.com/ODM2/conda-recipes-ODM2/blob/master/recipes/wofpy/meta.yaml).

Thanks.

**Comment by ocefpaf** [comment] 2016-08-15 14:13
> Pinging @ocefpaf, in case he has some additional insight/wisdom. Though like I said, I don't see a problem per se.

`wofpy` does have a dependency on `flask`, not sure if that is only for the examples though. See
https://github.com/ODM2/conda-recipes-ODM2/blob/master/recipes/wofpy/meta.yaml#L21

If that is optional, and not desirable as to be installed by default, I can change that in the recipe.

BTW `django` is a dependency of `spyne` and `wofpy` specifies the latter. So `django` is also installed.

I based the dependencies using `wofpy`'s `setup.py` specifications: https://github.com/ODM2/WOFpy/blob/master/setup.py#L55-L61

Let me know if any of those are not really needed.

> BTW, questions that are specific to conda packaging are probably better addressed as issues on the conda-recipes-ODM2 repo.

:+1:

**Comment by emiliom** [comment] 2016-08-15 18:39
@ocefpaf has provided (thanks!) a definitive answer to the question about Django:

> django is a dependency of `spyne` and `wofpy` specifies the latter. So django is also installed.

And to cover the `flask` part of @SRGDamia1's original question: `flask` is a core `wofpy` requirement.

Since the original questions asked on this issue have been answered, and there's no further action to be taken (unless @valentinedwv has something to add), I'm closing this issue.

**Closed by emiliom** 2016-08-15 18:39 UTC
